Language-File: 'en.yml'
Debug: false
Format:
  Symbol: '$'
  Single: 'Coin'
  Plural: 'Coins'
Database:
  Name: 'Lobby'
  MySQL:
    host: 'localhost'
    port: 3306
    database: 'root'
    username: 'root'
    password: 'password'